Algoritmo "Exercício_3"
// Disciplina   : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Troca o valor das variáveis
// Autor(a)    : Leandro Lima

Var
   VLR1, VLR2, troca : real


Inicio
   escreva("Digite o primeiro valor: ")
   leia(VLR1)
   escreva("Digite o segundo valor: ")
   leia(VLR2)
   troca <- VLR1
   VLR1 <- VLR2
   VLR2 <- troca
   escreval("Primeiro valor: ", VLR1)
   escreval("Segundo valor: ", VLR2)

Fimalgoritmo