Algoritmo "Exercício_4"
// Disciplina   : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Calcula média aritmética
// Autor(a)    : Leandro Lima

Var
   VLR1, VLR2, VLR3, media : real


Inicio
   escreva("Digite o primeiro valor: ")
   leia(VLR1)
   escreva("Digite o segundo valor: ")
   leia(VLR2)
   escreva("Digite o terceiro valor: ")
   leia(VLR3)
   media <- (VLR1 + VLR2 + VLR3) / 3
   escreval("Média aritmética = ", media)

Fimalgoritmo